// News-desk RSS discovery — tier 1 of the sourcing ladder (see
// .council/research/2026-07/news-sourcing-policy.md).
//
// Free, plain-fetch RSS in two tiers (defined in ./_feeds.mjs):
//
//   primary     the issuer's OWN newsroom — citable under the sourcing
//               ladder, and free, which is the point: the same release
//               read through a Firecrawl press-room monitor costs ~60
//               credits a month and arrives as a diff rather than a
//               dated, titled item.
//   aggregator  competitor coverage — DISCOVERY ONLY, never a fact base.
//
// Both land in the digest, under separate headings, so a desk can never
// mistake one for the other.
//
// The press-room tier that used to live here moved to native Firecrawl
// monitors on 2026-08 (scripts/monitor/, provisioned by setup.mjs as
// "dubaipoints-press-rooms"). The hand-rolled version scraped each press
// index and diffed headline links itself, which is what surfaced "Visit
// our Facebook page" as a story on its first live run; Firecrawl's own
// diff plus goal judging does that job properly. Press findings still
// land at .council/monitoring/digest-<stamp>.md, so nothing downstream
// changed.
//
// This file is now free to run — no Firecrawl key, no credit cap.
//
// Output: .council/monitoring/digest-<date>.md (only when something new)
// plus updated state in data/news-monitor/state.json.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const STATE_PATH = "data/news-monitor/state.json";

import { RSS_FEEDS, RELEVANT, parseFeed, hasLatin } from "./_feeds.mjs";

const state = existsSync(STATE_PATH)
  ? JSON.parse(readFileSync(STATE_PATH, "utf8"))
  : { seen: {} };

const now = new Date();
const newItems = [];

function remember(sourceId, key, item) {
  const bucket = (state.seen[sourceId] ??= []);
  if (bucket.includes(key)) return;
  bucket.push(key);
  if (bucket.length > 300) bucket.splice(0, bucket.length - 300);
  newItems.push(item);
}

// Tier 1 — RSS
for (const feed of RSS_FEEDS) {
  try {
    const res = await fetch(feed.url, {
      headers: { "user-agent": "dubaipoints-news-monitor/1.0 (+https://dubaipoints.ae)" },
      signal: AbortSignal.timeout(20000),
    });
    if (!res.ok) { console.error(`[rss] ${feed.id} HTTP ${res.status}`); continue; }
    const xml = await res.text();
    const parsed = parseFeed(xml).slice(0, 25);
    let kept = 0;
    for (const { title, link, date } of parsed) {
      if (!title || !link) continue;
      if (feed.latinOnly && !hasLatin(title)) continue;
      if (feed.filter !== false && !RELEVANT.test(title)) continue;
      kept++;
      remember(feed.id, link, {
        tier: feed.tier, source: feed.name, sourceId: feed.id,
        title, link, date: date ?? "",
        note:
          feed.tier === "primary"
            ? "PRIMARY SOURCE — the issuer's own newsroom. Citable; still read the release itself for every figure."
            : "DISCOVERY ONLY — verify every fact against a primary source before use.",
      });
    }
    console.log(`[rss] ${feed.id} ok (${feed.tier}, ${parsed.length} parsed, ${kept} kept)`);
  } catch (e) {
    console.error(`[rss] ${feed.id} failed: ${String(e).slice(0, 120)}`);
  }
}

// ── Output ────────────────────────────────────────────────────────────
mkdirSync("data/news-monitor", { recursive: true });
writeFileSync(STATE_PATH, JSON.stringify(state, null, 2));

if (newItems.length === 0) {
  console.log("No new items — no digest written.");
  process.exit(0);
}

const stamp = now.toISOString().slice(0, 16).replace("T", "-").replace(":", "");
const digestPath = `.council/monitoring/digest-${stamp}.md`;
mkdirSync(".council/monitoring", { recursive: true });

const lines = [
  `# News monitoring digest — ${now.toISOString().slice(0, 16).replace("T", " ")} UTC`,
  "",
  "_Auto-generated by scripts/news-monitor/monitor.mjs (GitHub Actions)._",
  "_Issuer-newsroom items are PRIMARY and may be cited. Aggregator items_",
  "_are DISCOVERY ONLY — a lead to chase, never a fact and never a number._",
  "",
  "_Press-room findings arrive separately, from the Firecrawl monitors_",
  "_polled by scripts/monitor/poll.mjs, in a digest at this same path._",
  "",
];
for (const [tier, heading] of [
  ["primary", "## Issuer newsrooms (primary — citable)"],
  ["aggregator", "## Aggregator RSS (discovery only)"],
]) {
  const rows = newItems.filter((i) => i.tier === tier);
  if (!rows.length) continue;
  lines.push(heading, "");
  for (const i of rows) {
    lines.push(`- **${i.title}**`);
    lines.push(`  ${i.source}${i.date ? ` · ${i.date}` : ""}`);
    lines.push(`  ${i.link}`);
    lines.push(`  _${i.note}_`);
    lines.push("");
  }
}
writeFileSync(digestPath, lines.join("\n"));
console.log(`Digest written: ${digestPath} (${newItems.length} new items)`);
