// News-desk RSS discovery — tier 1 of the sourcing ladder (see
// .council/research/2026-07/news-sourcing-policy.md).
//
// Competitor/aggregator RSS (free, plain fetch) — DISCOVERY ONLY. Titles
// and links land in the digest for the desks to chase via primary
// sources. Never a fact base.
//
// The press-room tier that used to live here moved to native Firecrawl
// monitors on 2026-08 (scripts/monitor/, provisioned by setup.mjs as
// "dubaipoints-press-rooms"). The hand-rolled version scraped each press
// index and diffed headline links itself, which is what surfaced "Visit
// our Facebook page" as a story on its first live run; Firecrawl's own
// diff plus goal judging does that job properly. Press findings still
// land at .council/monitoring/digest-<stamp>.md, so nothing downstream
// changed.
//
// This file is now free to run — no Firecrawl key, no credit cap.
//
// Output: .council/monitoring/digest-<date>.md (only when something new)
// plus updated state in data/news-monitor/state.json.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const STATE_PATH = "data/news-monitor/state.json";

// ── Tier 1: RSS discovery (free) ──────────────────────────────────────
const RSS_FEEDS = [
  { id: "hfp", name: "Head for Points", url: "https://www.headforpoints.com/feed/" },
  { id: "omaat", name: "One Mile at a Time", url: "https://onemileatatime.com/feed/" },
  { id: "lfal", name: "Live From A Lounge", url: "https://livefromalounge.com/feed/" },
  { id: "tpg", name: "The Points Guy", url: "https://thepointsguy.com/feed/" },
];

// UAE-relevance filter for RSS titles (press pages pass everything —
// they are already first-party and low-volume).
const RELEVANT = /\b(uae|dubai|abu dhabi|sharjah|dxb|auh|dwc|shj|emirates|skywards|etihad|flydubai|air arabia|qatar airways|avios|privilege club|alfursan|saudia|gcc|bonvoy|rotana|jumeirah|address hotels|staycation)\b/i;

const state = existsSync(STATE_PATH)
  ? JSON.parse(readFileSync(STATE_PATH, "utf8"))
  : { seen: {} };

const now = new Date();
const newItems = [];

function remember(sourceId, key, item) {
  const bucket = (state.seen[sourceId] ??= []);
  if (bucket.includes(key)) return;
  bucket.push(key);
  if (bucket.length > 300) bucket.splice(0, bucket.length - 300);
  newItems.push(item);
}

// Tier 1 — RSS
for (const feed of RSS_FEEDS) {
  try {
    const res = await fetch(feed.url, {
      headers: { "user-agent": "dubaipoints-news-monitor/1.0 (+https://dubaipoints.ae)" },
      signal: AbortSignal.timeout(20000),
    });
    if (!res.ok) { console.error(`[rss] ${feed.id} HTTP ${res.status}`); continue; }
    const xml = await res.text();
    const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0, 25);
    for (const [, body] of items) {
      const title = (body.match(/<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/) || [])[1]?.trim();
      const link = (body.match(/<link>([\s\S]*?)<\/link>/) || [])[1]?.trim();
      const date = (body.match(/<pubDate>([\s\S]*?)<\/pubDate>/) || [])[1]?.trim();
      if (!title || !link) continue;
      if (!RELEVANT.test(title)) continue;
      remember(feed.id, link, {
        tier: "rss", source: feed.name, sourceId: feed.id,
        title, link, date: date ?? "",
        note: "DISCOVERY ONLY — verify every fact against a primary source before use.",
      });
    }
    console.log(`[rss] ${feed.id} ok`);
  } catch (e) {
    console.error(`[rss] ${feed.id} failed: ${String(e).slice(0, 120)}`);
  }
}

// ── Output ────────────────────────────────────────────────────────────
mkdirSync("data/news-monitor", { recursive: true });
writeFileSync(STATE_PATH, JSON.stringify(state, null, 2));

if (newItems.length === 0) {
  console.log("No new items — no digest written.");
  process.exit(0);
}

const stamp = now.toISOString().slice(0, 16).replace("T", "-").replace(":", "");
const digestPath = `.council/monitoring/digest-${stamp}.md`;
mkdirSync(".council/monitoring", { recursive: true });

const lines = [
  `# News monitoring digest — ${now.toISOString().slice(0, 16).replace("T", " ")} UTC`,
  "",
  "_Auto-generated by scripts/news-monitor/monitor.mjs (GitHub Actions)._",
  "_RSS items are DISCOVERY ONLY — the sourcing ladder requires primary_",
  "_verification of every fact before publication._",
  "",
  "_Press-room findings arrive separately, from the Firecrawl monitors_",
  "_polled by scripts/monitor/poll.mjs, in a digest at this same path._",
  "",
];
{
  lines.push("## Aggregator RSS (discovery only)", "");
  for (const i of newItems) {
    lines.push(`- **${i.title}**`);
    lines.push(`  ${i.source}${i.date ? ` · ${i.date}` : ""}`);
    lines.push(`  ${i.link}`);
    lines.push(`  _${i.note}_`);
    lines.push("");
  }
}
writeFileSync(digestPath, lines.join("\n"));
console.log(`Digest written: ${digestPath} (${newItems.length} new items)`);
